//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHCMS.CORE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public string AppointmentId { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<byte> Slot { get; set; }
        public Nullable<byte> Token { get; set; }
        public string PatientId { get; set; }
        public string DoctorId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
