//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHCMS.CORE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialization
    {
        public string SpecializationId { get; set; }
        public string GujaratiTitle { get; set; }
        public string EnglishTitle { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    }
}
